### ISSUE TITLE
More model types

### ISSUE THREAD

**Issue by evanfeinberg** [pandegroup/deepchem#64]
We should be able to 1:1 compare ML technique performance with ease, akin to what's available with vanilla sk-learn. For example, it would be great for a user to directly compare a vanilla ```MLP``` with a random forest regressor, but the latter is not currently included as an option. Perhaps there is a not too cumbersome way for us to create an interface with sklearn to make many of its techniques automatically available, so we do not have to manually create a convenience class for each? If not, we should make a few more convenience classes for ```deepchem``` that wraps around ```sklearn``` techniques.

**Comment by rbharath** [comment]
This is fixed by #82.
